markdown: kramdown
kramdown:
  parse_block_html: true

theme: jekyll-theme-minimal
title: Example title
description: Description of the example site
show_downloads: true

#remote_theme: pages-themes/dinky@v0.2.0
#plugins:
#- jekyll-remote-theme