markdown: kramdown
kramdown:
  toc_levels      : [2, 3]
  parse_block_html: true

# Block parsing is needed for closeable sections

theme: jekyll-theme-minimal
title: Example title
description: Description of the example site
show_downloads: true